### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by VanessaAoki** [VanessaAoki/JS-Capstone#24]
https://github.com/VanessaAoki/JS-Capstone/projects/1

We are 2 people working on this capstone, @Chike1990 is Student A and @VanessaAoki is Student B.

**Comment by henatan99** [comment]
Hi @VanessaAoki && @Chike1990 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
